[font]
size = 17.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[colors.primary]
background = "#000000"
foreground = "#c5c8c6"

[env]
TERM = "alacritty"

[scrolling]
history = 10000

# [shell]
# program = "/opt/homebrew/bin/nu"

[window.padding]
x = 0
y = 0
