[colors.primary]
background = "#000000"
foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 10000

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "None"

[window.padding]
x = 14
y = 14

[general]
import = ["/home/sugan/.config/omarchy/current/theme/alacritty.toml"]

[terminal]

